### ISSUE TITLE
Magento2.3 not supported xdebug3

### ISSUE THREAD

**Issue by srsathish92** [rewardenv/reward#13]
Hi @janosmiko ,

I am facing an issue with the latest reward env with Magento2.3.

## Steps to reproduce:
- Install Magento 2.3 with php7.3
- Connect to Xdebug with phpstrom using `XDEBUG_SESSION=PHPSTORM`. 
- You could see error in Magento like below
![image](https://user-images.githubusercontent.com/18184256/152991074-c6b963cd-d570-4a8d-aebc-17491ed8158d.png)
- Comment out below line then the above issue will resolve.
`if (!(bool)$debugMode && extension_loaded('xdebug')) {
    xdebug_disable();
}`
- After that, Phpstorm breakpoint not working.

## Additional Information:
- _**Magento 2.3 only supports Xdebug 2**_
- Phpstorm breakpoint works before `reward env pull`
- ![image](https://user-images.githubusercontent.com/18184256/153004727-6fbb7c4d-8726-4d0b-8619-9191aa8a3c55.png)

## Expected Result:
- Phpstorm breakpoint should work with Xdebug3 and Magento2.3 or would like to know "how to downgrade the Xdebug version".

Please let me know If require additional information's.

Thanks
Sathish

**Comment by janosmiko** [comment]
As the upstream repository does not support Xdebug 2 packages, I decided to create a dedicated Docker image, which builds Xdebug2 with PECL.

If you'd like to use Xdebug2, you will have to add the following line to your `.env` file:
```
XDEBUG_VERSION=2
```

https://rewardenv.readthedocs.io/en/latest/configuration/xdebug.html
