### ISSUE TITLE
(elementaryOS 6.1 - Ubuntu 20.04) Error: your operating system is not supported. Yet. :(

### ISSUE THREAD

**Issue by OliverBeckwith** [rewardenv/reward#19]
Hi, I am trying to install Reward on elementaryOs 6.1, which is built on Ubuntu 20.04 (which the Reward documentation claims works). Is there some way to run `reward install` with a parameter to tell it to assume it is on Ubuntu 20.04?

Here is my OS info if it helps:
```
$ cat /etc/os-release
NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal
```

**Comment by janosmiko** [comment]
Hi @OliverBeckwith ,

I added elementary to the supported Operating Systems. It should work with Reward 0.2.30-beta.

**Comment by OliverBeckwith** [comment]
Hi Janos. Thank you. It now installs without any errors. However, after running `reward install` and then `reward svc up`, I cannot access any of the global services described [here](https://rewardenv.readthedocs.io/en/latest/services.html). I have tried restarting my laptop and then rerunning `reward svc up` (and then tried both commands together again), and still nothing. I don't know if this is related to the previous issue though.

**Comment by OliverBeckwith** [comment]
My apologies. I had missed the DNS resolution step of the installation process. All is working perfectly now. Thank you for your help

**Comment by janosmiko** [comment]
I'm happy to hear that!
