### ISSUE TITLE
"Cannot connect to remote host" while trying to connect to DB with PHPStorm

### ISSUE THREAD

**Issue by adexandros** [rewardenv/reward#2]
I tried connecting PHPStorm to a project DB like I did many other times with warden; I followed the guide but I keep getting the error "Cannot connect to remote host"  while setting up the SSH Tunnel;

I also tried connecting to it from the CLI:
`$ sudo ssh magento@tunnel.reward.test -p 2222`
`magento@tunnel.reward.test: Permission denied (publickey,keyboard-interactive).`

I can post a more verbose error message from the terminal if needed

Am I missing some step here? All the other services work correctly, as well as PHPmyadmin

**Comment by janosmiko** [comment]
Hello @adexandros !

To connect to the ssh tunnel, you should use 'user' as the ssh username.

https://rewardenv.readthedocs.io/en/latest/configuration/db.html

**Comment by adexandros** [comment]
Hi @janosmiko , I posted the wrong example code but initially I tried with `user` and that didn't work either; this is my PHPStrom setup:
![Screenshot 2021-03-18 182045](https://user-images.githubusercontent.com/5301695/111677021-b149e480-8816-11eb-96c7-417a28071647.png)

**Comment by janosmiko** [comment]
Could you show me the output of `reward svc ps` and `ls -lah ~/.reward/tunnel`.

Also could you try to connect with `ssh -i ~/.reward/tunnel/ssh_key -l user -p 2222 tunnel.reward.test`

**Comment by adexandros** [comment]
```
~/projects/ba/hanes-eagle$ reward svc ps
   Name                 Command               State                      Ports
--------------------------------------------------------------------------------------------------
dnsmasq      /bin/sh -c  echo "$REWARD_ ...   Up      127.0.0.1:53->53/udp
elastichq    supervisord -c /etc/superv ...   Up      5000/tcp
mailhog      MailHog                          Up      1025/tcp, 8025/tcp
phpmyadmin   /docker-entrypoint.sh apac ...   Up      80/tcp
portainer    /portainer                       Up      8000/tcp, 9000/tcp
traefik      /entrypoint.sh traefik           Up      127.0.0.1:443->443/tcp, 127.0.0.1:80->80/tcp
tunnel       /entry.sh /usr/sbin/sshd - ...   Up      127.0.0.1:2222->22/tcp
```

```
ls -lah ~/.reward/tunnel
ls: cannot access '/home/adexandros/.reward/tunnel': No such file or directory
```

```
$ ssh -i ~/.reward/tunnel/ssh_key -l user -p 2222 tunnel.reward.test
Warning: Identity file /home/adexandros/.reward/tunnel/ssh_key not accessible: No such file or directory.
user@tunnel.reward.test: Permission denied (publickey,keyboard-interactive).
```

I guess it cannot find the folder since reward is installed on windows? Should I copy the folder from window to inside WSL2?

**Comment by adexandros** [comment]
The command `$ ssh -i ~/.reward/tunnel/ssh_key -l user -p 2222 tunnel.reward.test` works if executed from Windows Powershell

**Comment by janosmiko** [comment]
Could you try to configure PHPStorm SSH Authentication type to use "Key Pair" and browse the ssh key from your default Windows home? 
Something like `c:\Users\yourname\.reward\tunnel\ssh_key`

**Comment by adexandros** [comment]
Hi @janosmiko , that actually worked and I can connect to the database perfectly 👍🏻 
I got 2 more questions if you are able to answer:
* Is there a way to pass directly arguments too `reward db connect` ? for example when making install scripts that needs to send command for DB operations.
* When I use the global service phpmyadmin, how can I connect to the different available projects DBs? When I use just user/pass I am only able to access the DB of the first project I started basically; if I put a server name like <project>_db_1 I am not able to log in

**Comment by janosmiko** [comment]
Hi @adexandros !

## Pass args directly to `reward db connect`

Yes it's possible.

You can use bash's double dash scheme "--". This is going to terminate reward's command line options and the rest is going to be passed as arguments.
So if you call `reward db connect -- asd qwe` then the part after double dash (asd qwe) will be passed directly to mysql command inside the container.

From mysql manual:
  -e, --execute=name  Execute command and quit. (Disables --force and history
                      file.)

So we can use `-- -e` to run commands directly by mysql. Please note that in this case bash will try to handle the special characters so you will have to escape quotes, double quotes, semicolons and maybe more.

``` bash
$ reward db connect -- -e \"show databases\;\"
+--------------------+
| Database           |
+--------------------+
| information_schema |
| magento            |
+--------------------+

$ reward db connect -- -e \"select table_name from information_schema.tables where table_schema=\'magento\' order by table_name limit 5\;\"
+-----------------------------------+
| table_name                        |
+-----------------------------------+
| adminnotification_inbox           |
| admin_analytics_usage_version_log |
| admin_passwords                   |
| admin_system_messages             |
| admin_user                        |
+-----------------------------------+
```


An idea to keep you code cleaner would be to use bash variables here. An important thing here as well if you just assign a command to a bash variable that's not going to have the trailing double quotes (see the first example):
``` bash
# This is not going to work:
$ MYSQL_CMD="select table_name from information_schema.tables where table_schema='magento' order by table_name limit 5;"

$ echo $MYSQL_CMD
select table_name from information_schema.tables where table_schema='magento' order by table_name limit 5;


# But this will work:
$ MYSQL_CMD="\"select table_name from information_schema.tables where table_schema='magento' order by table_name limit 5;\""

$ echo $MYSQL_CMD
"select table_name from information_schema.tables where table_schema='magento' order by table_name limit 5;"
^ -- note the quotes are part of the variable here

# This will also work:
$ MYSQL_CMD=$(cat <<"EOF"
"select table_name from information_schema.tables where table_schema='magento' order by table_name limit 5;"
EOF
)

$ echo $MYSQL_CMD
"select table_name from information_schema.tables where table_schema='magento' order by table_name limit 5;"

$ reward db connect -- -e $MYSQL_CMD
+-----------------------------------+
| table_name                        |
+-----------------------------------+
| adminnotification_inbox           |
| admin_analytics_usage_version_log |
| admin_passwords                   |
| admin_system_messages             |
| admin_user                        |
+-----------------------------------+

```



## On your second question
You can check the "hostname" of your db container by running `reward env ps db`.
```
reward env ps db
 Name                Command               State    Ports
-----------------------------------------------------------
m2_db_1   docker-entrypoint.sh mysql ...   Up      3306/tcp
```

And you should be able to use this name (for me its m2_db_1).

Please make sure your phpmyadmin container is connected to the environment's container network.

To list the networks your phpmyadmin container is joined you can run the following command:
```
docker inspect --format='{{range $key, $value := .NetworkSettings.Networks}}{{$key}} {{end}}' phpmyadmin
```

**Comment by janosmiko** [comment]
I updated the documentation, hopefully now makes more sense:
https://rewardenv.readthedocs.io/en/latest/usage.html
https://rewardenv.readthedocs.io/en/latest/configuration/db.html

**Comment by adexandros** [comment]
Hi @janosmiko , that's great news and information; I run the command to check which network phpmyadmin is connected to and it only list one of my projects; how do I add another one to it? is this something that needs to be done for each new project created?

**Comment by janosmiko** [comment]
Well that's interesting.

When you run `reward env up` reward should connect phpmyadmin to the environment's network.

Could you try to run `reward env down` and then `reward env up`?

If you enable debug mode, you should see something like this:
![screenshot](https://i.imgur.com/PgKm6Dx.png)

**Comment by adexandros** [comment]
Thanks that did the trick 👍🏻
