### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by OliverBeckwith** [rewardenv/reward#20]
Hi. After getting everything going I have noticed that the certificates are not being accepted by any of my browsers (they acknowledge that they exist but don't like them anyway).

I have tried on the following and had the same issue:
Google Chrome
Google Chrome - Incognito
GNOME Web

![Screenshot from 2022-03-18 11-33-33](https://user-images.githubusercontent.com/23747711/158995950-db092f7d-e2ff-4c02-8866-e808fa40fdbc.png)

I can simply proceed to the site anyway so this is not a big issue, but thought it was worth reporting.

**Comment by janosmiko** [comment]
Hi @OliverBeckwith !

You will have to add the root CA certificate to chrome's CA database. You can find how to do it in the docs (in the note section):
https://rewardenv.readthedocs.io/en/latest/installation.html#trusted-ca-root-certificate


Also I suggest you to join Reward's Slack where you can ask questions like these.
http://rewardslack.janosmiko.com/
