### ISSUE TITLE
Xdebug 2 on PHP 7.0

### ISSUE THREAD

**Issue by tzoli96** [rewardenv/reward#23]
Hi,
I using reward on php7.0,it couldn't pull Xdebug version 2.
I got these following error:
`Pulling php-debug (docker.io/rewardenv/php-fpm:7.0-magento2-xdebug2)...
ERROR: manifest for rewardenv/php-fpm:7.0-magento2-xdebug2 not found: manifest unknown: manifest unknown
Error: exit status 1
`
I am not sure why this happens, just noticed while started a new project on 7.0 PHP version.
I think this repository dosen't exits.

**Comment by janosmiko** [comment]
Hi @tzoli96 ,

The version of Xdebug2 we used previously only supports PHP 7.1+.

Now I added a special build to support PHP 5.6 and 7.0.

Please try now.
