### ISSUE TITLE
Laravel APP_KEY not updated after key generation

### ISSUE THREAD

**Issue by zoltan-nemeth-born** [rewardenv/reward#3]
Hey!

I created a new Laravel project from scrath with following the guide:
https://rewardenv.readthedocs.io/en/latest/environments/initializing-laravel.html

Step 5. Create an APP_KEY and add it to the .env file.
Key generated successfully and I copied the generated key to the .env file (to the APP_KEY row)

After that I regenerate the config cache with
 `php artisan config:cache.`

and the application cache with 
`php artisan cache:clear`

The application throws an error, the key not valid. Repeated a new key and it was the same.

**Issue**: I check the config.php in the cache directory and an old key present here, the generate:key or the copy+paste not modified the key in the cached config file..

**Comment by janosmiko** [comment]
Hi @zoltan-nemeth-born ,

I tried to clear all the caches as well, but couldn't determine the issue in Reward, so I tried to dig deeper.
I found that it's not that easy to change the APP_KEY for a Laravel application. 

You will have to rotate your APP_KEY (and the settings, which are encrypted using the APP_KEY).

You can find further reading here:
https://github.com/techsemicolon/laravel-app-key-rotation

However, if you run `reward env down` and `reward env up` which is going to recreate your PHP-FPM containers, you will be able to regenerate the bootstrap/cache/config.php using the new key, but I think you will loose some settings, which were encrypted with the previous key.

**Comment by janosmiko** [comment]
I also updated the docs to use laravel's built in key generation.

**Comment by zoltan-nemeth-born** [comment]
Hey @janosmiko !

Thank you!

**Comment by janosmiko** [comment]
Hi @zoltan-nemeth-born 

I found the solution. Actually when Reward calls docker-compose, it passes the .env file as [env-file](https://docs.docker.com/compose/environment-variables/#using-the---env-file--option). So if you change it in runtime, you will have to reload the env.
``` bash
# previous key
www-data@lara-php-fpm:/var/www/html$ grep -E 'key.*base64' bootstrap/cache/config.php
    'key' => 'base64:CwxhRyt/b2VXVk7jgpitPC+79Yr+C5YH9a5NJlF4nkk=',

# generate a new key
www-data@lara-php-fpm:/var/www/html$ php artisan key:generate --show
base64:lrYlLbunGy3CX2diZH7M634jhDn4C5lNh7RtNWgVf68=

# add it to .env
www-data@lara-php-fpm:/var/www/html$ vim .env

# import .env
www-data@lara-php-fpm:/var/www/html$ source .env

www-data@lara-php-fpm:/var/www/html$ php artisan cache:clear
Application cache cleared!
www-data@lara-php-fpm:/var/www/html$ php artisan config:cache
Configuration cache cleared!
Configuration cached 
 
www-data@lara-php-fpm:/var/www/html$ grep -E 'key.*base64' bootstrap/cache/config.php
    'key' => 'base64:lrYlLbunGy3CX2diZH7M634jhDn4C5lNh7RtNWgVf68=',
```

**Comment by zoltan-nemeth-born** [comment]
Hey @janosmiko !

It's works! Thank you very much! 

It's Reward Env is one of the best tool for PHP developers! Thank you for your work and the free sharing!

**Comment by janosmiko** [comment]
But keep in mind, the previous solution is going to update env vars for your current session only. 

A more permanent option is to simply run `reward env up` (even if it's running), which is going to recreate the php-fpm container with your the environment variables.

**Comment by janosmiko** [comment]
Thank you so much! 
I really appreciate it!
