### ISSUE TITLE
Composer 1 being used instead of Composer 2

### ISSUE THREAD

**Issue by leoner-omnipro** [rewardenv/reward#33]
### Steps
1. Clone Magento project
2. Modify `.env` (optional)
3. Import db
4. Run `reward bootstrap`

This was working fine with Composer 2 until I updated rewardenv, now whenever I start a project it appears that it uses Composer 1 to install the dependencies when Composer 2 is recommended.
- Docker desktop with WSL2
- Ubuntu 22.04
- Magento version `magento/magento-cloud-metapackage[2.4.1]`

Also, I've tried using `sudo alternatives --config composer` to select the version Composer, but when I run the bootstrap command, it uses Composer 1 again

### Screenshots
![Untitled](https://user-images.githubusercontent.com/93623882/210408719-b82da19e-5429-4539-b515-9809f4cdf98f.png)

**Comment by janosmiko** [comment]
Hi @leoner-omnipro !

Could you provide your `.env` file, and your reward version please?

**Comment by leoner-omnipro** [comment]
> Hi @leoner-omnipro !
> 
> Could you provide your `.env` file, and your reward version please?
> 
> In an older version of Reward it enforced the Composer version based on the Magento version (enforce to use composer2 for magento 2.4.2+ or something similar) but I removed that as someone requested to remove it.
> 
> Now you can enforce the composer version using the `COMPOSER_VERSION=1/2` variable in the `.env` file.

Sure, here the reward version
![image](https://user-images.githubusercontent.com/93623882/210439265-9cdcaec8-2079-469d-ba2c-2fa274eaa3a9.png)

and the .env file
```env
REWARD_ENV_NAME=testing-magento
REWARD_ENV_TYPE=magento2
REWARD_WEB_ROOT=/

TRAEFIK_DOMAIN=testing-magento.test
TRAEFIK_SUBDOMAIN=
TRAEFIK_EXTRA_HOSTS=

REWARD_DB=1
REWARD_ELASTICSEARCH=0
REWARD_OPENSEARCH=1
REWARD_OPENSEARCH_DASHBOARDS=0
REWARD_VARNISH=1
REWARD_RABBITMQ=1
REWARD_REDIS=1
REWARD_MERCURE=0

ELASTICSEARCH_VERSION=7.16
OPENSEARCH_VERSION=1.2
MARIADB_VERSION=10.4
NODE_VERSION=16
PHP_VERSION=7.4
RABBITMQ_VERSION=3.8
REDIS_VERSION=6.0
VARNISH_VERSION=6.5
COMPOSER_VERSION=2

REWARD_SYNC_IGNORE=

REWARD_ALLURE=0
REWARD_SELENIUM=0
REWARD_SELENIUM_DEBUG=0
REWARD_BLACKFIRE=0
REWARD_SPLIT_SALES=0
REWARD_SPLIT_CHECKOUT=0
REWARD_TEST_DB=0
REWARD_MAGEPACK=0

BLACKFIRE_CLIENT_ID=
BLACKFIRE_CLIENT_TOKEN=
BLACKFIRE_SERVER_ID=
BLACKFIRE_SERVER_TOKEN=

XDEBUG_VERSION=
```

**Comment by janosmiko** [comment]
I think I found the issue. I will publish the fix tomorrow. Stay tuned 👌

**Comment by janosmiko** [comment]
It should be fixed now. @leoner-omnipro please let me know if the issue still occurs with v0.3.25-beta

**Comment by leoner-omnipro** [comment]
> It should be fixed now. @leoner-omnipro please let me know if the issue still occurs with v0.3.25-beta

Working again!
Only this warning appears, but I don't think it's anything to worry about.

![image](https://user-images.githubusercontent.com/93623882/210562832-2f5cbde3-d6a9-497e-ba22-025331a35dec.png)
