### ISSUE TITLE
Unnavailable to use Xdebug

### ISSUE THREAD

**Issue by leoner-omnipro** [rewardenv/reward#36]
Hey!
I'm trying to use Xdebug for debug Magento2 modules, the configuration seems to be good but when try to enable debug mode it just isn' working. I connected to container to see logs of ngix and I'm getting this message
```bash
[error] 46#46: *328 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.21.0.1:9003 (from HTTP_X_DEBUG_HOST HTTP header), localhost:9003
```

### Technical Specifications
- Docker desktop with WSL2
- Ubuntu 22.04
- Magento version `magento/magento-enterprise-metapackage[2.4.5]`
- Reward version 
![image](https://user-images.githubusercontent.com/93623882/221665404-e09bdd4e-d67d-4b76-9a03-ec023c38891c.png)

#### Server
![image](https://user-images.githubusercontent.com/93623882/221666358-ceaae21d-2aa9-4750-982e-e6253ed5aa5b.png)

#### CLI Interpreter
Here I added some changes to test, but nothing works
![image](https://user-images.githubusercontent.com/93623882/221666692-f06b15c6-2cdb-4d72-9ca7-1d88fe5140ab.png)

#### Debug settings
![image](https://user-images.githubusercontent.com/93623882/221666878-2e22c9b4-9b19-4a7a-a9e8-fbfa023a8591.png)

#### Remote debug settings
![image](https://user-images.githubusercontent.com/93623882/221667110-07e0823a-6f8a-492a-90ac-3ad4bfb3aa88.png)

Just let me know pls if I'm missing something in configurations, Thanks!

**Comment by janosmiko** [comment]
Hi @leoner-omnipro 

You can try to configure this in the `.env` file:
```
XDEBUG_REMOTE_HOST=host.docker.internal 
```

Sadly it's quite complicated to setup Xdebug on WSL2 and it's out of the scope of Reward. 

See these articles:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/4406842719378-Setting-up-debugging-with-XDebug-3-and-WSL2?page=1#comments
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010615740-Xdebug3-WSL2

**Comment by leoner-omnipro** [comment]
> Hi @leoner-omnipro
> 
> You can try to configure this in the `.env` file:
> 
> ```
> XDEBUG_REMOTE_HOST=host.docker.internal 
> ```
> 
> Sadly it's quite complicated to setup Xdebug on WSL2 and it's out of the scope of Reward.
> 
> See these articles: https://intellij-support.jetbrains.com/hc/en-us/community/posts/4406842719378-Setting-up-debugging-with-XDebug-3-and-WSL2?page=1#comments https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010615740-Xdebug3-WSL2

I already tried this config in the additional options of CLI configuration, works on different way? Or maybe I'm choosing the wrong container

**Comment by mekedron** [comment]
Hi @janosmiko @leoner-omnipro 
The same issue on clear Ubuntu 22.04.
Temp solution is:
```shell
reward debug
echo "xdebug.client_host=host.docker.internal" >> /etc/php/8.1/fpm/conf.d/xdebug.ini
echo "xdebug.client_host=host.docker.internal" >> /etc/php/8.1/cli/conf.d/xdebug.ini
exit
reward env stop php-debug ; reward env up php-debug
```

**Comment by janosmiko** [comment]
I updated the xdebug containers to contain those settings. I also created a new release (v0.4.3) with various bug fixes.

Could you try if it's working now?
```console
$ reward self-update
$ reward env pull
$ reward env up -- php-debug
$ reward debug
www-data@m2-php-debug:/var/www/html$ cat /etc/php/8.1/fpm/conf.d/php-fpm.ini
[php]
memory_limit=-1

[xdebug]
xdebug.mode=debug,trace,profile
xdebug.start_with_request=trigger
xdebug.client_host=host.docker.internal

www-data@m2-php-debug:/var/www/html$ cat /etc/php/8.1/cli/conf.d/php-cli.ini
[php]
memory_limit=-1

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
```

After adding a custom value to my `.env` and I restart the debug container, it's updated as well:

```console
$ echo XDEBUG_REMOTE_HOST=123.232.123.42 >> .env
$ reward env up -- php-debug
$ reward debug
www-data@m2-php-debug:/var/www/html$ cat /etc/php/8.1/fpm/conf.d/php-fpm.ini
[php]
memory_limit=-1

[xdebug]
xdebug.mode=debug,trace,profile
xdebug.start_with_request=trigger
xdebug.client_host=123.232.123.42
```

**Comment by mekedron** [comment]
Thank you @janosmiko!
I'll test it shortly

**Comment by mekedron** [comment]
Hey @janosmiko 
Thanks, xdebug works as expected on clear Ubuntu 22.04

**Comment by leoner-omnipro** [comment]
I can confirm that it is working as expected, tysm! 🚀
