### ISSUE TITLE
Unable to receive or send Webhooks to Stripe

### ISSUE THREAD

**Issue by Chris-Kiddier** [rewardenv/reward#39]
Hi,

This may to completely out of the scope of these issues, but I thought I'd give it a shot:

I'm working with Stripe and Magento and, ideally, I'd like to expose my local site to Stripes API in order to receive their webhook responses. I usually get a 'failed to connect' error, I assume due to that docker is running locally and not exposed?

Are there any configurations I can change in order to expose Reward to Stripe?

I originally tried - reward_traefik_listen: 0.0.0.0 in the .reward.yml, but that did not affect the Stripe webhooks being sent back.

If you've any ideas, that would be ace otherwise I will look elsewhere,

Thanks again for making this docker system!

**Comment by janosmiko** [comment]
Hi @Chris-Kiddier ,

I'm not sure how that works, but I assume the Stipe API requires a publicly accessible URL (including a valid domain and all the network stuff, like routing/proxying the external requests to your machine).
I think the easiest way to make your local environment publicly accessible is by using ngrok:

https://ngrok.com/

**Comment by Chris-Kiddier** [comment]
OK thanks, I will give that a try!
