### ISSUE TITLE
Move complex build-time operations from Dockerfile to shell scripts

### ISSUE THREAD

**Issue by szepeviktor** [rewardenv/reward#45]
1. Tool installations
2. Configuration file creations

```dockerfile
COPY ./scripts.sh /usr/local/bin/reward-scripts.sh
SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]
RUN source reward-scripts.sh \
    install_magerun
```

There are many identical blocks of code.
What do you think?

**Comment by janosmiko** [comment]
Definitely a good idea, there are many duplications in the Dockerfiles

**Comment by szepeviktor** [comment]
Docker has a feature
```dockerfile
RUN --mount=type=bind,source="$(pwd)"/target,target=/app
```

**Comment by szepeviktor** [comment]
Tasty 👨🏻‍🍳 
https://github.com/szepeviktor/docker-RUN-file/actions/runs/5386685816/jobs/9777022336

**Comment by szepeviktor** [comment]
This is how to move scripts from Dockerfile to a file:
https://github.com/szepeviktor/docker-RUN-file/blob/master/Dockerfile#L3
