### ISSUE TITLE
ngrok testing?

### ISSUE THREAD

**Issue by joseborngroup** [rewardenv/reward#5]
Hi, this rewardenv is great, but is there any way to test the local environment using ngrok? when I run the ngrok command  `./ngrok http https://mywebsite.test` and then I try to open the url provided by ngrok, then I am always getting '404 page not found'. Thanks so much

**Comment by janosmiko** [comment]
Hi @joseborngroup !

Well I never used this stuff before. 

Could you please be a bit more specific about it? 

What's the purpose of ngrok?
What environment type did you use? 
How should I implement it?

Also any contributions are more than welcome here so feel free to create a pull request.

**Comment by joseborngroup** [comment]
Hi, thanks for replying, ngrok is basically to share your localhost website with someone else through a public url that ngrok provides [https://ngrok.com/docs](https://ngrok.com/docs) , you can basically run a command `ngrok http 80` and ngrok will give you a public url ie. http://92832de0.ngrok.io  forwarding to your locahost. I am using a Magento 2 Reward Environment. Also I have noticed, it is not possible to access the reward environment by just calling the host and the port on browser, I am trying to call https://127.0.0.1:80 but this doesn't display the https://mywebsite.test website. So I also wonder what is the host and the port that rewardenv uses?

**Comment by janosmiko** [comment]
Well that's by a good purpose.

The main functionality of Reward is to be able to run multiple environments simultaneously.
In front of your Magento environment Reward runs a Traefik container which proxies the requests (based on the Host header) to the different Magento environments.

Anyway. I was able to run ngrok like this:

```
# get current environment name
ENV=$(cat .env | grep 'REWARD_ENV_NAME' | cut -d '=' -f2)

# get current docker network name
NETWORK=$(docker network ls --filter=label=dev.reward.environment.name=${ENV} --format "{{.Name}}")

# get current nginx container
NGINX=$(docker ps --filter name=${ENV}_nginx --format '{{.Names}}')

# run ngrok container in the same network and link it to the nginx container
docker run --rm -it --link $NGINX --net $NETWORK wernight/ngrok ngrok http $NGINX:80
```

I had to change the magento base url to reflect to the ngrok url.

**Comment by igi8819** [comment]
For me this cmd also working
`./ngrok http -host-header=rewrite your-url.test:443`  
OR
`./ngrok http -host-header=rewrite your-url.test:80`  

Just need to download ngrok (https://ngrok.com/) and need to add ngrok authtoken for port 443

So now your url is accessible from outside just without css/images...

For magento 2 it is a temp solution but you can try this:

Open: 
vendor/magento/framework/App/Http.php

Add these 3 lines before "return $this->_response;"

```
$body = $this->_response->getBody();
$body = str_replace('https://your-url.test/', 'https://your-ngrok-url.ngrok.io/', $body);
$this->_response->setBody($body);
```
