### ISSUE TITLE
DNS Port 53 unavailable due to new Docker update

### ISSUE THREAD

**Issue by OliverBeckwith** [rewardenv/reward#56]
![image](https://github.com/rewardenv/reward/assets/23747711/f59f4fcd-fef7-4a20-85c6-03639df27638)

**Comment by janosmiko** [comment]
It looks like this issue is on the radar of the Docker Desktop team.
https://github.com/docker/for-mac/issues/7008

They also provide a workaround until it's fixed:
https://docs.docker.com/desktop/release-notes/#known-issues

> Creating a container with the port 53 fails with the error address already in use. As a workaround, deactivate network acceleration by adding `"kernelForUDP": false,` in the settings.json file located at `~/Library/Group Containers/group.com.docker/settings.json`.

It's out of the scope of Reward so I close this.
