### ISSUE TITLE
Ngnix 413 configuration

### ISSUE THREAD

**Issue by zoltan-nemeth-born** [rewardenv/reward#6]
Szia @janosmiko !
Az egyik projektben az adminisztrációs felületen ki szeretnénk exportálni egy kicsit nagyobb mennyiségű cart price rule-t, de 413 Request Entity Too Large  Nginx hibát kapok (legfrissebb Rewardenv környezet).

Log:
`nginx_1          | 2021/07/05 10:57:08 [error] 31#31: *1 client intended to send too large body: 6445603 bytes, client: 172.24.0.14, server: , request: "POST /admin/sales_rule/promo_quote/exportCouponsCsv/key/7acb1de050992dd4f9fc903004892f170842028e7a7ab3acf48ae1f36db86cc5/id/7/filter/Y3JlYXRlZF9hdCU1QmxvY2FsZSU1RD1lbl9VUyZleHBpcmVzX2F0JTVCbG9jYWxlJTVEPWVuX1VTJnVzZWQ9MA%3D%3D/?ajax=true&isAjax=true HTTP/1.1", host: "champion237.test", referrer: "https://champion237.test/admin/sales_rule/promo_quote/edit/id/7/key/12d5ce65967805a9bcc0b605925902027afe18c50166d258d724f916f5f91c64/"`

Hogyan tudnám frissíteni az Nginx konfigurációt az admin felületre, hogy ezt a nagyobb mennyiségű adatot is feldolgozza?
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

Köszönöm szépen!

**Comment by janosmiko** [comment]
Hali @zoltan-nemeth-born !

Próbáld meg ezt:

Tegyél le egy fájlt a környezeten belül a `.reward/nginx` mappába és tedd bele a konfigot, amire szükséged van:
(Fontos, hogy a fájl neve server-*.conf legyen.)

```
13:45:44 in .../Workspace/test/m2 via 🐘 v7.3.24 took 46s
➜ cat .reward/nginx/server-body.conf
client_max_body_size 64M;

13:45:51 in .../Workspace/test/m2 via 🐘 v7.3.24
➜ reward env restart -- nginx
Restarting m2_nginx_1 ... done
```

Két ilyen dinamikus konfigurálás van az nginx-hez beépítve. Egyikkel a http blokkhoz tudsz extra változókat felvenni (http-*.conf) másikkal pedig a szerver (server-*.conf) blokkba.
https://github.com/rewardenv/reward/blob/91be60f909c7778d15349ec5409da65e6a3c946e/images/nginx/context/etc/nginx/conf.d/default.conf.template#L23

**Comment by zoltan-nemeth-born** [comment]
@janosmiko Szia! Szuper, működik! Köszönöm a gyors választ! :)
