### ISSUE TITLE
XDebug manual initiation

### ISSUE THREAD

**Issue by anthonysan95** [rewardenv/reward#63]
Could you please add the check in the nginx default.conf map for xdebug manual initiation parameters? (https://xdebug.org/docs/step_debug#manual-init)
Either $arg_XDEBUG_SESSION or $arg_XDEBUG_SESSION_START is fine.

I've got a case where I need to debug but I can't set the cookie.
This allows me to do for example this:
https://app.test/rest/products?XDEBUG_SESSION_START=PHPSTORM
and debug the request without cookies.

I issued the same request on warden:
https://github.com/wardenenv/images/issues/16

Thanks.

**Comment by janosmiko** [comment]
Thanks for your suggestion @anthonysan95 .

I added this feature in the following commit:
https://github.com/rewardenv/reward/commit/85720741b39c7c57b85392c4401b25edc3595e67#diff-0b066e1f3efd0081d8b670c35afffefbb163f158745adb3f9d01f3a0090ee072
