### ISSUE TITLE
Reward can be updated without sudo permissions

### ISSUE THREAD

**Issue by Mr-Leonerrr** [rewardenv/reward#64]
### Description
Is it normal to be allowed to update without having sudo user permissions?
![image](https://github.com/rewardenv/reward/assets/56647065/ad044cbf-90e5-4be2-bf36-15f581f660eb)

**Comment by janosmiko** [comment]
I cannot reproduce it on a clean Ubuntu install, and the permissions of the binary looks good to me.

![CleanShot 2024-02-06 at 09 42 59@2x](https://github.com/rewardenv/reward/assets/693558/23e387a3-6f00-4b61-a8c9-499b16352fe5)

What are the permissions of the reward binary for you?

**Comment by Mr-Leonerrr** [comment]
There the permissions
![image](https://github.com/rewardenv/reward/assets/56647065/594bec46-99cd-4321-b481-a7a2790d98b0)

**Comment by janosmiko** [comment]
@Mr-Leonerrr could you also show us the perms of the /usr/bin directory?

I asked a bunch of colleagues to try it out but we cannot reproduce this issue. :(

**Comment by Mr-Leonerrr** [comment]
@janosmiko sure, but there are a lot of folders,
![image](https://github.com/rewardenv/reward/assets/56647065/665b0ce0-bef3-4a81-9846-d79c33bd8de6)
