### ISSUE TITLE
Error during "reward install" in Ubuntu 22.4 with Docker Compose

### ISSUE THREAD

**Issue by zaheerbadi** [rewardenv/reward#65]
Title: Error during "reward install" in Ubuntu 22.4 with Docker Compose

**Issue:**

I am encountering an error while attempting to execute the "reward install" command in Ubuntu 22.4 with the following Docker and Docker Compose versions:

- **Ubuntu OS Version:** 22.4
- **Docker Compose Version:** 1.29.2, build unknown
- **Docker Version:** 25.0.3, build 4debf41

**Error Description:**

Upon running the "reward install" command, I am receiving an error message in my command-line interface. The error seems to impede the successful execution of the command, and I'm unable to proceed with the installation process.

**Steps to Reproduce:**

1. Execute the command: `reward install`
2. Observe the error message returned by the command.

**Error Message:**

![image](https://github.com/rewardenv/reward/assets/9264676/839f37e3-026e-4484-bbdd-6c27a456f802)[Attach the image of the error message displayed in the CLI here]

**Additional Context:**

I have ensured that the Docker and Docker Compose versions are up to date, and I have followed the installation instructions meticulously. Despite these efforts, I am consistently encountering this error.

**Screenshot Attachment:**

![image](https://github.com/rewardenv/reward/assets/9264676/839f37e3-026e-4484-bbdd-6c27a456f802)[Attach the screenshot of the error message displayed in the CLI here]

**Expected Behavior:**

I expect the "reward install" command to execute successfully without encountering any errors, thereby completing the installation process as intended.

Any insights or guidance on resolving this issue would be greatly appreciated. Thank you for your assistance in advance.

**Comment by janosmiko** [comment]
Hi @zaheerbadi ,

Could you guide me a bit? How you installed docker compose?
And which version of docker do you use? Regular docker or docker desktop?

**Comment by zaheerbadi** [comment]
I installed docker-compose with the guidance of reward documentation.

Docker Version: 25.0.3, build 4debf41

**Comment by zaheerbadi** [comment]
I just removed docker-compose using PIP and installed using apt-get and it started working
