### ISSUE TITLE
Docker error after upgrade

### ISSUE THREAD

**Issue by Mr-Leonerrr** [rewardenv/reward#67]
### Description
Hi, I upgraded reward to **v0.6.0**, but now, when trying to start any environment or just view the environment information, I get several error messages related to Docker.
Is it necessary to perform any additional process after upgrading?

-- reward info
![image](https://github.com/rewardenv/reward/assets/56647065/bac0b8db-4e33-4d9f-b98a-5703db6662b0)

-- reward env start
![image](https://github.com/rewardenv/reward/assets/56647065/94b78c49-c4f5-4f27-8cfd-9de96d75fee7)

### System Information
INFO    reward version: 0.6.0
INFO    GOOS: linux
INFO    GOARCH: amd64

#### Docker information
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by janosmiko** [comment]
Hi @Mr-Leonerrr 

Could you show me which reward version do you use?

```
reward version
```

**Comment by Mr-Leonerrr** [comment]
Sure
![image](https://github.com/rewardenv/reward/assets/56647065/5bda190e-f29e-4813-a178-01bbea55f085)

**Comment by janosmiko** [comment]
Please run a forceful upgrade and try again:
```
(sudo) reward self-upgrade --force
```

**Comment by Mr-Leonerrr** [comment]
It says that my version is not the latest 🤔

![image](https://github.com/rewardenv/reward/assets/56647065/d3e57171-ad3c-46f8-a1f6-9480ac2a6daf)

**Comment by janosmiko** [comment]
That's not a problem, if you run it forcefully it will upgrade it anyway.

**Comment by Mr-Leonerrr** [comment]
Okay, now is working again. I started the project directly in the Docker Desktop interface, when I use `reward env start` is throws an error with the `traefik` container, even when the service container is running
![image](https://github.com/rewardenv/reward/assets/56647065/fa4c47b7-9ac9-4269-a90a-3c75ab43aa44)

![image](https://github.com/rewardenv/reward/assets/56647065/0542e6d3-a2c5-424e-bbfd-dcbbb9e07dbe)

**Comment by janosmiko** [comment]
Probably you should shut down and start the project again, because in this release we changed from docker compose v1 to v2.

```
reward env down
reward svc down
reward svc up
reward env up
```

**Comment by janosmiko** [comment]
Hi @Mr-Leonerrr ,

Have you tried these commands in the last comment? Can we close this issue?

**Comment by Mr-Leonerrr** [comment]
Hey @janosmiko!
I've not tried it yet, since I have several projects that could be affected if I go through this process. We can close the issue and any situation I will be leaving the comment, thank you very much for your answers.

Have a great day 🚀

**Comment by Mr-Leonerrr** [comment]
Hey @janosmiko!

I tried running the commands.
First, the `reward env down -v` command
![imagen](https://github.com/rewardenv/reward/assets/56647065/5afb8d47-458b-4e8a-a1fe-85bf031b17d3)

And then, the `reward svc down` and `reward svc up`
![imagen](https://github.com/rewardenv/reward/assets/56647065/6d193995-bcf3-432b-9b45-0e92349450f2)

Maybe related with the Docker version?

**Comment by janosmiko** [comment]
Hi @Mr-Leonerrr 

Could you check your docker desktop if the traefik container is stucked there (or something is running that's binding to port 80)?

**Comment by Mr-Leonerrr** [comment]
These are the services that were activated, the traefik container appears "created".

![image](https://github.com/rewardenv/reward/assets/56647065/12af198b-64fd-475a-9a87-7165028c8357)

**Comment by Mr-Leonerrr** [comment]
It seems that some Windows service is using that port, which blocks the use for another service.
I solved it by changing the port in the configuration file (`\\wsl.localhost\Ubuntu-22.04\home\my-user\.reward.yml`) to port `81` and then rerunning `reward svc up` (it sets the port to the default one, so have to change again to `81` after run)

![image](https://github.com/rewardenv/reward/assets/56647065/9dd4559b-4ec8-4429-a06c-dab904a6c1fe)

Thanks a lot for the support!
