### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RedSign77** [rewardenv/reward#7]
Szia @janosmiko !

Frissen telepített Ubuntu 20.04, feltettem a Reward-ot és rendben ment is az első projekttel. A második projektet akartam indítani, azonban az env-init a következő hibát dobja és utána folyamatosan:

```
reward env-init project2

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x61e271]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0, 0xc0001b7800, 0x13)
	/home/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.2.1/version.go:363 +0x51
github.com/rewardenv/reward/cmd.init.1()
	/home/runner/work/reward/reward/cmd/bootstrap.go:69 +0x86d
```

A két projekt között kellett egy ssh kulcsot generálnom, de ezenkívül más lényeges változás nem történt. Van valami javaslatod, hogy mi lehet a gond?

Köszönöm szépen,
Zoli

**Comment by janosmiko** [comment]
Hali!

El tudod küldeni a .env fájlt (ha létrejött) és a package.json fájlt (ha van ilyen)?

Üdv,
Jani

**Comment by RedSign77** [comment]
Szia!

Nem jött létre, package.json-ból meg csak a sample van. A composer.json-t néztem ez egy régebbi magento 2.3.1-es volt és 2.3.5-p1-re lett felhúzva. Eléggé hack-elt állapotban örökölt projekt, szóval nem biztos, hogy a Reward-dal van baj, főleg, hogy a másik projektnél gond nélkül megy.

Szerintem megcsinálom, hogy üres mappába inicializálók egy új környezetet (env-init), beállíttom az .env file-t és beleteszem a kódot a mappába. Ez lehet megoldás vagy így is belefutok ebbe?

Köszönöm,
Zoli

**Comment by janosmiko** [comment]
A composer.json-re gondoltam, bocsi.

Szerintem az a -p1 lesz a gond a Magento verzió végén. A [library](https://github.com/hashicorp/go-version), amit használ a reward, nem biztos, hogy támogatja ezt a postfixet. 

Utánajárok és jelentkezem.

**Comment by RedSign77** [comment]
@janosmiko Értem, köszönöm szépen előre is! :)

**Comment by janosmiko** [comment]
It Turned out the issue was caused by the `^` in the beginning of the Magento Package Version in composer.json.

It is fixed with the following commits:
f6ee33357e57a692ff566558f4e8de37cd834fce
84f1325d81d59381d8e281137d77204b66a6f6a6

**Comment by RedSign77** [comment]
Thank you @janosmiko ! Perfect!
