### ISSUE TITLE
NGINX_PUBLIC variable not working in REWARD_ENV_TYPE=generic-php

### ISSUE THREAD

**Issue by srsathish92** [rewardenv/reward#70]
The `NGINX_PUBLIC` variable is not working in REWARD_ENV_TYPE=generic-php which means not routing properly.

**Sample .env**
```
REWARD_ENV_NAME=phpproject
REWARD_ENV_TYPE=generic-php
REWARD_WEB_ROOT=/www

TRAEFIK_DOMAIN=phpproject.test
TRAEFIK_SUBDOMAIN=
TRAEFIK_EXTRA_HOSTS=

REWARD_DB=true
REWARD_REDIS=true

MARIADB_VERSION=10.6
NODE_VERSION=16
PHP_VERSION=8.3
REDIS_VERSION=6.0
COMPOSER_VERSION=2

MYSQL_ROOT_PASSWORD=app
MYSQL_DATABASE=app
MYSQL_USER=app
MYSQL_PASSWORD=app

NGINX_ROOT=/var/www/html
NGINX_PUBLIC=/public
```
**Folders**
```
/project/www
/project/www/public
/project/www/public/index.php
```
**Reward Shell:**
```
/var/www/html
/var/www/html/public
/var/www/html/public/index.php
```
**Expected Results:** index,php should load If I run phpproject.test
**Actual Issue:** nginx config/mapping not working properly

Please let me know If you require more information.
Thanks

**Comment by janosmiko** [comment]
Hello @srsathish92 ,

Thank you for your bug report. Sadly, I'm unable to reproduce it. I copied the `.env` file you created, created a public directory with an index.php in it and added the following:
```php
<?php
phpinfo();
?>
```

And here's the result:
![CleanShot 2024-10-07 at 19 18 32@2x](https://github.com/user-attachments/assets/10622076-dda7-4a14-ad6b-f77ba7837d02)

**Comment by janosmiko** [comment]
I also tried it with a fresh install on ubuntu 24.04 and works there as well:
![CleanShot 2024-10-07 at 20 25 05@2x](https://github.com/user-attachments/assets/0ebdd531-42a1-434b-a019-b254898e4be9)

**Comment by janosmiko** [comment]
Cannot reproduce the issue
