### ISSUE TITLE
kdeneon | running install command: your operating system is not supported. yet. :( 

### ISSUE THREAD

**Issue by xborderMaske** [rewardenv/reward#72]
Hello, in a same way as the issue https://github.com/rewardenv/reward/issues/19, Im trying to install reward in a ubuntu- like OS (kdeneon), but this throw the error "your operating system is not supported. yet. :( "

Can add this OS or the OS with ID_LIKE as ubuntu?
thanks!

```
cat /etc/os-release
PRETTY_NAME="KDE neon 6.1"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="6.0"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=jammy
LOGO=start-here-kde-neon
```

**Comment by janosmiko** [comment]
Hello @xborderMaske ,

It should be fixed with the latest release.

**Comment by xborderMaske** [comment]
Hello @janosmiko , Im getting the same error.

![image](https://github.com/user-attachments/assets/33af01ad-42dd-4c9d-8999-49b8a3cd5ba1)

I look at the code and think that is missing in [this file certs.go:153](https://github.com/rewardenv/reward/blob/8a18dc79524d4f401e513482a5b337d1d91730af/internal/crypto/certs.go#L153).

```go
switch osDistro {
	case "windows":
		return c.windowsInstallCACertificate(caCertificatePEMFilePath)

	case "darwin":
		return c.darwinInstallCACertificate(caCertificatePEMFilePath)

	case "ubuntu", "debian", "pop", "elementary", "linuxmint":
		return c.debianInstallCACertificate(caCertificatePEMFilePath)

	case "fedora", "centos":
		return c.rhelInstallCACertificate(caCertificatePEMFilePath)

	case "arch", "manjaro":
		return c.archInstallCACertificate(caCertificatePEMFilePath)

	default:
		return errors.New("your operating system is not supported. yet. :(")
	}
```

![Error after `A Certificate created.`](https://github.com/user-attachments/assets/43bc59ae-c7b7-46d8-9145-d45c24147189)

**Comment by janosmiko** [comment]
@xborderMaske you are right, added it there too and preparing a release now.

**Comment by xborderMaske** [comment]
thank you very much! @janosmiko

I omited this part on the install and face with another issue, related to the DNS bind, but see in other issue, seem to be related with docker.

**Comment by xborderMaske** [comment]
now run all ok, thanks!!!
the problem with dns was that some time ago I install bind9 and the service was running in my machine...
my fault.
