### ISSUE TITLE
Docker compose version warning on -desktop release

### ISSUE THREAD

**Issue by Mr-Leonerrr** [rewardenv/reward#74]
Since a few updates ago, I am getting this warning in the terminal every time any command is used. I think it's because the installed version doesn't meet the SemVer standard in this case. Is there any way I can avoid this message?

![image](https://github.com/user-attachments/assets/1b236d45-6af5-4afb-b816-4ffd499a3127)

**REWARD INFO**
INFO    reward version: 0.6.13+202410181344
INFO    GOOS: linux
INFO    GOARCH: amd64

**DOCKER INFO**
Docker Compose version v2.29.7-desktop.1
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:39:44 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop  ()
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by janosmiko** [comment]
Fixed in v0.6.14
