### ISSUE TITLE
Feature Request: Sylius

### ISSUE THREAD

**Issue by RedSign77** [rewardenv/reward#9]
Szia @janosmiko !

Nemrég találtam meg a Sylius-t, ami hasonló mint a Magento csak kisebb és gyorsabb és Symfony alapokra épített.
Megoldható lenne az integrációja a környezetedbe?
Itt található a dokumentáció hozzá: https://docs.sylius.com/en/latest/getting-started-with-sylius/installation.html

Köszönöm szépen,
Zoli

**Comment by janosmiko** [comment]
I completely forget to close this issue.

So as Sylius is Symfony based, you can use a regular Symfony install process:

```
mkdir ~/Workspace/test/sylius
cd ~/Workspace/test/sylius
reward env-init sylius --environment-type=symfony
reward sign-certificate sylius.test

reward env up
reward shell

composer create-project --no-install --no-interaction --no-scripts \
    sylius/sylius-standard /tmp/sylius-tmp

rsync -au --remove-source-files /tmp/sylius-tmp/ /var/www/html/

composer config --global process-timeout 2000
composer install

bin/console sylius:install

yarn install
yarn build
```
